spring:
    # HTTP ENCODING
    http:
       encoding.charset: UTF-8
       encoding.enable: true
       encoding.force: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${env.hostname.eureka:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
name:
  hehe