server:
  port: 9090

# SPRING PROFILES
spring:
    # DATASOURCE
  datasource:
    name: druidDataSource
    url: jdbc:mysql://120.77.148.33:4406/test?useUnicode=true&useSSL=true&characterEncoding=utf-8
    username: root
    password: 7224
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#mybatis config
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.yb.chat.entity
  mapperLocations: classpath*:mappers/*.xml
